config/routes.rb
Assessment::Application.routes.draw do
  devise_for :users, skip: :registrations

  resources :papers do
    resources :parts
    resources :nodes
    member do
      get 'publish', :as => 'publish'
    end
  end

  resources :organizations
  resources :members

  resources :uploads, :only => [:index, :create, :destroy]

  resources :tests do
    resources :questions do
      resource :solution
    end

    collection do
      get 'take', :as => 'take'
    end
  end

  root :to => 'dashboard#index'

end

app/controllers/parts_controller.rb
# -*- encoding : utf-8 -*-
class PartsController < ApplicationController
  before_filter :can_index, :only => [:index]
  before_filter :can_show, :only => [:show]
  before_filter :can_create, :only => [:new, :create]
  before_filter :can_update, :only => [:edit, :update, :destroy]

  #before_filter :load_paper
  add_breadcrumb '试卷列表', :papers_path

  def index
    @parts = @paper.partial_papers

    add_breadcrumb '单项设置', :paper_parts_path
  end

  def new
    @part = Paper.new
    @part.type = 'partial'
  end

  def create
    @part = Paper.new(params[:paper])
    @part.type = 'partial'
    @part.has_parts = false
    @part.general_paper = @paper

    if @part.save
      redirect_to paper_parts_path
    else
      render 'new'
    end
  end

  def edit
    #@part = Paper.find(params[:id])
  end

  def update
    #@part = Paper.find(params[:id])

    if @part.update_attributes(params[:paper])
      redirect_to paper_parts_path(@paper), :notice => '更新单项试卷成功'
    else
      render 'edit'
    end
  end

  def destroy
    #@part = Paper.find(params[:id])

    if @part.update_attribute(:status, :deleted)
      redirect_to paper_parts_path(@paper), :notice => '删除成功'
    else
      render 'index'
    end

  end

  private
  #def load_paper
  #  @paper = Paper.find(params[:paper_id])
  #  render_404 unless @paper.has_parts?
  #end

  def can_index
    @paper = Paper.find(params[:paper_id])
    render_404 and return unless current_user.root?
  end

  def can_create
    @paper = Paper.find(params[:paper_id])
    render_404 and return unless current_user.root?

    render_404 and return unless @paper.draft?
  end

  def can_show
    @paper = Paper.find(params[:paper_id])
    @part = Paper.find(params[:id])
    render_404 and return unless current_user.root? && @part.partial? && @part.paper_id == @paper.id
  end

  def can_update
    @paper = Paper.find(params[:paper_id])
    @part = Paper.find(params[:id])
    render_404 and return unless current_user.root? && @part.partial? && @part.paper_id == @paper.id

    render_404 and return unless @paper.draft?
    render_404 and return if @part.deleted?
  end
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/parts/edit.html.erb
<%= simple_form_for @part, :url => paper_part_path(@paper, @part), :html => {:class => 'form-horizontal'} do |f| %>
    <fieldset>
        <legend>综合试卷：<%= @paper.name %></legend>

        <%= f.input :name, :label => '单项试题名称', :required => true %>

        <%= f.input :score, :label => '单项分数', :required => true %>

        <%= f.input :duration, :label => '限时(分)', :required => true  %>

        <%= f.input :notice, :label => '注意事项', :as => 'text', :input_html => {:rows => 3} %>
    </fieldset>

    <div class="form-actions">
      <%= submit_tag '保存', :class => 'btn btn-primary' %>
      <a href="<%= url_for(:back) %>" class="btn">取消</a>
    </div>
<% end %>

app/views/parts/index.html.erb
<a href="<%= new_paper_part_path(@paper) %>" class="btn btn-small btn-success pull-right">新增单项</a>

<ul class="nav nav-tabs">
  <li>
    <a href="<%= edit_paper_path(@paper) %>">试题信息</a>
  </li>
  <% if @paper.has_parts? %>
      <li class="active"><a href="<%= paper_parts_path(@paper) %>" >单项设置</a></li>
      <% @paper.partial_papers.each do |part| %>
          <li><a href="<%= paper_nodes_path(part) %>"><%= part.name %></a></li>
      <% end %>
  <% else %>
      <li><a href="<%= paper_nodes_path(@paper) %>" >试卷内容</a></li>
  <% end %>
</ul>

<table class="table table-striped">
  <caption></caption>
  <thead>
  <tr>
    <th>单项试卷名称</th>
    <th>分数</th>
    <th>限时（分）</th>
    <th>操作</th>
  </tr>
  </thead>
  <tbody>
  <% if @parts.blank? %>
      <tr placeholder>
        <td colspan="4">本综合试卷未划分单项试题</td>
      </tr>
  <% end %>
  <% @parts.each do |part| %>
      <tr>
        <td><%= part.name %></td>
        <td><%= part.score %></td>
        <td><%= part.duration %></td>
        <td>
           <% if part.deleted? %>
                已删除
           <% else %>
               <a href="<%= edit_paper_part_path(@paper, part) %>" class="btn btn-mini">编辑</a>
               <%= link_to '删除', paper_part_path(@paper, part), :method => 'DELETE', :confirm => '你确定删除此单项，其下的所有考题也将一并删除?', :class => 'btn btn-danger btn-mini' %>
           <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
  <tfoot>

  </tfoot>
</table>

app/views/parts/new.html.erb
<%= simple_form_for @part, :url => paper_parts_path(@paper), :html => {:class => 'form-horizontal'} do |f| %>
    <fieldset>
        <legend>综合试卷：<%= @paper.name %></legend>

        <%= f.input :name, :label => '单项试题名称', :required => true %>

        <%= f.input :score, :label => '单项分数', :required => true %>

        <%= f.input :duration, :label => '限时(分)', :required => true  %>

        <%= f.input :notice, :label => '注意事项', :as => 'text', :input_html => {:rows => 3} %>
    </fieldset>

    <div class="form-actions">
      <%= submit_tag '保存', :class => 'btn btn-primary' %>
      <a href="<%= url_for(:back) %>" class="btn">取消</a>
    </div>
<% end %>