config/routes.rb
Assessment::Application.routes.draw do
  devise_for :users, skip: :registrations

  resources :papers do
    resources :parts
    resources :nodes
    member do
      get 'publish', :as => 'publish'
    end
  end

  resources :organizations
  resources :members

  resources :uploads, :only => [:index, :create, :destroy]

  resources :tests do
    resources :questions do
      resource :solution
    end

    collection do
      get 'take', :as => 'take'
    end
  end

  root :to => 'dashboard#index'

end

app/models/node.rb
class Node < ActiveRecord::Base
  set_inheritance_column ''

  TYPES = %w[material question]
  MEDIA = %w[text audio]
  PATTERNS = %w[single-choice]

  def material?
    type == 'material'
  end

  def question?
    type == 'question'
  end

  # depth废弃
  attr_accessible :type, :media, :content, :depth, :weight,
                  :pattern, :answer, :grade,
                  :node_id, :choices_attributes

  belongs_to :paper

  belongs_to :material, :class_name => 'Node', :foreign_key => 'node_id'
  has_many :questions, :class_name => 'Node', :dependent => :nullify

  has_many :choices, :dependent => :destroy

  has_one :answer, :class_name => 'Choice', :foreign_key => 'answer'

  accepts_nested_attributes_for :choices, :allow_destroy => true, :reject_if => proc { |attributes| attributes['content'].blank? }

  after_create :set_answer_from_choices, :if => :question?

  #---------------------------验证-------------------------------------------
  validates :type, :media, :content, :weight, :presence => true
  validates :pattern, :grade, presence: true, if: 'question?'
  validates :grade, length: { maximum: 5 }, numericality: { only_integer: true }, if: 'question?'

   private

  def set_answer_from_choices
     choices.each do |choice|
       answer = choice.id if choice.is_answer?
     end
  end
end

app/controllers/nodes_controller.rb
# -*- encoding : utf-8 -*-
class NodesController < ApplicationController
  before_filter :can_index, :only => [:index]
  before_filter :can_show, :only => [:show]
  before_filter :can_create, :only => [:new, :create]
  before_filter :can_update, :only => [:edit, :update, :destroy]

  def index
    #@nodes = Node.order('weight asc').where(:depth => 1, :paper_id => @paper.id).map do |node|
    @nodes = Node.find_by_sql(["select * from nodes where (type='material' or node_id is null) and paper_id = ? order by weight asc", @paper.id]).map do |node|
      node.questions.sort!() if node.material?
      node
    end
  end

  def new
    @node = Node.new
    @node.paper = @paper
    @node.type = params[:type] || 'question'

    if @node.material?
      render 'new_material'
    else
      @materials = Node.where(:type => 'material', :paper_id => @paper.id).map {|material| [material.content, material.id]}
      render 'new_question'
    end
  end

  def create
    @node = Node.new(params[:node])
    @node.paper = @paper
    #@node.depth = @node.material? || @node.node_id.blank? ? 1 : 2

    if @node.save
      redirect_to paper_nodes_path(@paper), :notice => "#{t('dict.'+@node.type)}创建成功"
    else
      if @node.material?
        render 'new_material'
      else
        @materials = Node.where(:type => 'material', :paper_id => @paper.id).map {|material| [material.content, material.id]}
        render 'new_question'
      end
    end
  end

  def edit
    #@node = Node.find(params[:id])

    if @node.material?
      render 'edit_material'
    else
      @materials = Node.where(:type => 'material', :paper_id => @paper.id).map {|material| [material.content, material.id]}
      render 'edit_question'
    end
  end

  def update
    #@node = Node.find(params[:id])
    @node.assign_attributes(params[:node])
    #@node.depth = @node.material? || @node.node_id.blank? ? 1 : 2

    if @node.save
      redirect_to paper_nodes_path(@paper)
    else
      render 'edit'
    end
  end

  def destroy
    #@node = Node.find(params[:id])

    if  @node.destroy
      redirect_to paper_nodes_path(@paper), :notice => '删除成功'
    else
      render 'index'
    end

  end

  private
  #def load_paper
  #  @paper = Paper.find(params[:paper_id])
  #  # 只允许单项以及没有任何单项的综合试卷允许编辑考试题
  #  render_404 if @paper.general? && @paper.has_parts?
  #end

  def can_index
    @paper = Paper.find(params[:paper_id])
    render_404 and return unless current_user.root?
  end

  def can_create
    @paper = Paper.find(params[:paper_id])
    render_404 and return unless current_user.root?

    if @paper.general?
      render_404 and return if @paper.has_parts?
      render_404 and return unless @paper.draft?
    end

    if @paper.partial?
      render_404 and return if @paper.deleted?
      render_404 and return unless @paper.general_paper.draft?
    end
  end

  def can_show
    @paper = Paper.find(params[:paper_id])
    @node = Node.find(params[:id])

    render_404 and return unless current_user.root?
  end

  def can_update
    @paper = Paper.find(params[:paper_id])
    @node = Node.find(params[:id])

    render_404 and return unless current_user.root?

    if @paper.general?
      render_404 and return if @paper.has_parts?
      render_404 and return unless @paper.draft?
    end

    if @paper.partial?
      render_404 and return if @paper.deleted?
      render_404 and return unless @paper.general_paper.draft?
    end
  end

end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/nodes/edit_material.html.erb
<div id="material-form" class="well">
  <%= simple_form_for [@paper, @node], :html => {:class => 'form-horizontal'} do |f| %>
      <fieldset>
        <legend>材料</legend>

        <input name="node[type]" type="hidden" value="<%= @node.type %>" >
        <!--<%= f.input :type, :label => '类型', :required => true, :collection => dict(Node::TYPES), :prompt => '请选择..', :disabled => true  %>-->

        <%= f.input :weight, :label => '权重', :required => true, :help => '权重影响在同一级中的问题排序'  %>

        <%= f.input :media, :label => '媒体', :required => true, :collection => [dict(Node::MEDIA)[0]], :prompt => '请选择..'  %>

        <%= f.input :content, :label => '材料内容', :required => true, :as => 'text', :input_html => {:rows => 8, :class => 'rich-editor'} %>

        <div id="audio-uploader-div" class="control-group hide" style="margin-top: -15px">
          <!--<label class="string optional control-label" for="node_file"></label>-->
          <div class="controls">
            <input type="file" id="audio-uploader" name="file" >
          </div>
        </div>

      </fieldset>

      <div class="form-actions">
        <%= submit_tag '保存', :class => 'btn btn-primary' %>
        <a href="<%= url_for(:back) %>" class="btn">取消</a>
        <!--%= submit_tag '取消', :type => :reset, :class => "btn" %-->
      </div>

  <% end %>
</div>

app/views/nodes/edit_question.html.erb
<div id="question-form" class="well">
  <%= simple_form_for [@paper, @node], :html => {:class => 'form-horizontal'} do |f| %>
      <fieldset>
        <legend>题目</legend>

        <input name="node[type]" type="hidden" value="<%= @node.type %>" >
        <!--<%= f.input :type, :label => '类型', :required => true, :collection => dict(Node::TYPES), :prompt => '请选择..', :disabled => true %>-->

        <%= f.input :weight, :label => '权重', :required => true, :help => '权重影响在同一级中的问题排序' %>

        <%= f.input :media, :label => '媒体', :required => true, :collection => dict(Node::MEDIA), :prompt => '请选择..' %>

        <%= f.input :content, :label => '问题', :required => true, :as => 'text', :input_html => {:rows => 8, :class => 'rich-editor'}, :readonly =>  @node.media == 'audio' %>

        <div id="audio-uploader-div" class="control-group <%= @node.media == 'audio' ? '' : 'hide' %>" style="margin-top: -15px">
          <!--<label class="string optional control-label" for="node_file"></label>-->
          <div class="controls">
            <input type="file" id="audio-uploader" name="file" accept="audio/mpeg" >
          </div>
        </div>

        <%= f.input :pattern, :label => '题型', :required => true, :collection => dict(Node::PATTERNS), :prompt => '请选择..' %>

        <%= f.input :choices, :label => '选择项', :required => true do %>
            <table>
              <tbody>
              <% @node.choices.each do |choice| %>
                  <tr>
                    <td><input type="hidden" name="node[choices_attributes][][is_answer]" value=""></td>
                    <td><input type="radio" name="node[choices_attributes][][is_answer]" <%= 'checked' if choice.is_answer?  %> value="1" title="请选定正确答案"></td>
                    <td><input type="text" name="node[choices_attributes][][content]" value="<%= choice.content %>"></td>
                    <input type="hidden" name="node[choices_attributes][][id]" value="<%= choice.id %>">
                    <td><a class="remove-choice btn btn-mini icon-minus-sign"></a></td>
                  </tr>
              <% end %>
              <script id="choice-template" type="text/html">
                <tr>
                  <td><input type="hidden" name="node[choices_attributes][][is_answer]" value=""></td>
                  <td><input type="radio" name="node[choices_attributes][][is_answer]" title="请选定正确答案"></td>
                  <td><input type="text" name="node[choices_attributes][][content]"></td>
                  <td><a class="remove-choice btn btn-mini icon-minus-sign"></a></td>
                </tr>
              </script>
              </tbody>
              <tfoot>
              <tr>
                <td></td>
                <td colspan="2"><a class="add-choice btn btn-mini icon-plus-sign"></a></td>
              </tr>
              </tfoot>
            </table>
        <% end %>

        <%= f.input :grade, :label => '分值', :required => true %>

        <%= f.input :node_id, :label => '参考题干', :collection => @materials, :prompt => '无', :help => '如无参考材料，可留空' %>

      </fieldset>

      <div class="form-actions">
        <%= submit_tag '保存', :class => 'btn btn-primary' %>
        <a href="<%= url_for(:back) %>" class="btn">取消</a>
        <!--%= submit_tag '取消', :type => :reset, :class => "btn" %-->
      </div>

  <% end %>
</div>

app/views/nodes/index.html.erb
<div class="btn-group pull-right">
  <a class="btn btn-small btn-success" href="<%= new_paper_node_path(@paper, :type => 'material') %>">新增题干</a>
  <a class="btn btn-small btn-success" href="<%= new_paper_node_path(@paper, :type => 'question')  %>">新增问题</a>
</div>

<ul class="nav nav-tabs">
  <li>
    <a href="<%= edit_paper_path(@paper.partial? ? @paper.general_paper : @paper) %>">试卷信息</a>
  </li>
  <% if @paper.partial? %>
      <li><a href="<%= paper_parts_path(@paper.general_paper) %>" >单项设置</a></li>
      <% @paper.general_paper.partial_papers.each do |part| %>
          <li class="<%= 'active' if part.id == @paper.id %>"><a href="<%= paper_nodes_path(part) %>"><%= part.name %></a></li>
      <% end %>
  <% else %>
      <li class="active"><a href="<%= paper_nodes_path(@paper) %>" >试卷内容</a></li>
  <% end %>
</ul>

总分：<%= @paper.score %>
限时：<%= @paper.duration %>

<div class="tab-content">
  <div class="tab-pane fade in active" id="questions">
    <% num = 0 %>
    <% @nodes.each do |node| %>
    <dl>
      <% if node.material? %>
          <dt style="position: relative">
            <% if node.media == 'audio' %>
            <audio src='<%= node.content %>' preload="preload" />
            <% else %>
            <%= raw(node.content) %>
            <% end %>

            <div class="bar hide" style="position: absolute; top: 0px; right: 0px">
              <a class="btn btn-mini" href="<%= edit_paper_node_path(@paper, node) %>">编辑</a>
              <%= link_to '删除', paper_node_path(@paper, node), :method => 'DELETE', :confirm => '你确定删除此题干?', :class => 'btn btn-mini btn-danger'  %>
             </div>
          </dt>
          <% node.questions.each do |question| %>
              <dd style="position: relative">
                <span style="border: solid 1px"><%= num += 1 %></span>.
                <% if question.media == 'audio' %>
                    <audio src='<%= question.content %>' preload="none" autobuffer="true"></audio>
                <% else %>
                    <%= raw(question.content) %>
                <% end %>

                <div class="bar hide" style="position: absolute; top: 0px; right: 0px">
                  <a class="btn btn-mini" href="<%= edit_paper_node_path(@paper, question) %>">编辑</a>
                  <%= link_to '删除', paper_node_path(@paper, question), :method => 'DELETE', :confirm => '你确定删除此考题?', :class => 'btn btn-mini btn-danger'  %>
                </div>
                <ol>
                <% question.choices.each do |choice| %>
                  <li class="<%= 'answer' if choice.is_answer? %>"><%= choice.content %> </li>
                <% end %>
                </ol>

              </dd>
          <% end %>
      <% else %>
          <dd style="position: relative">
            <span style="border: solid 1px"><%= num += 1 %></span>.
            <% if node.media == 'audio' %>
                <audio src='<%= node.content %>' preload="none" autobuffer="true"></audio>
            <% else %>
                <%= raw(node.content) %>
            <% end %>
            <div class="bar hide" style="float: right;">
              <a class="btn btn-mini" href="<%= edit_paper_node_path(@paper, node) %>">编辑</a>
              <%= link_to '删除', paper_node_path(@paper, node), :method => 'DELETE', :confirm => '你确定删除此题目?', :class => 'btn btn-mini btn-danger'  %>
            </div>
            <ol>
              <% node.choices.each do |choice| %>
                  <li class="<%= 'answer' if choice.is_answer? %>"><%= choice.content %></li>
              <% end %>
            </ol>
          </dd>
      <% end %>
    </dl>
    <% end %>
  </div>
</div>

app/views/nodes/new_material.html.erb
<div id="material-form" class="well">
  <%= simple_form_for [@paper, @node], :html => {:class => 'form-horizontal'} do |f| %>
      <fieldset>
        <legend>材料</legend>

        <input name="node[type]" type="hidden" value="<%= @node.type %>" >
        <!--<%= f.input :type, :label => '类型', :required => true, :collection => dict(Node::TYPES), :prompt => '请选择..', :disabled => true  %>-->

        <%= f.input :weight, :label => '权重', :required => true, :help => '权重影响在同一级中的问题排序'  %>

        <%= f.input :media, :label => '媒体', :required => true, :collection => [dict(Node::MEDIA)[0]], :prompt => '请选择..'  %>

        <%= f.input :content, :label => '材料内容', :required => true, :as => 'text', :input_html => {:rows => 8, :class => 'rich-editor'} %>

        <div id="audio-uploader-div" class="control-group hide" style="margin-top: -15px">
          <!--<label class="string optional control-label" for="node_file"></label>-->
          <div class="controls">
            <input type="file" id="audio-uploader" name="file" >
          </div>
        </div>

      </fieldset>

      <div class="form-actions">
        <%= submit_tag '保存', :class => 'btn btn-primary' %>
        <a href="<%= url_for(:back) %>" class="btn">取消</a>
        <!--%= submit_tag '取消', :type => :reset, :class => "btn" %-->
      </div>

  <% end %>
</div>

app/views/nodes/new_question.html.erb
<div id="question-form" class="well">
  <%= simple_form_for [@paper, @node], :html => {:class => 'form-horizontal'} do |f| %>
      <fieldset>
        <legend>题目</legend>

        <input name="node[type]" type="hidden" value="<%= @node.type %>" >
        <!--<%= f.input :type, :label => '类型', :required => true, :collection => dict(Node::TYPES), :prompt => '请选择..', :disabled => true %>-->

        <%= f.input :weight, :label => '权重', :required => true, :help => '权重影响在同一级中的问题排序' %>

        <%= f.input :media, :label => '媒体', :required => true, :collection => dict(Node::MEDIA), :prompt => '请选择..' %>

        <%= f.input :content, :label => '问题', :required => true, :as => 'text', :input_html => {:rows => 8, :class => 'rich-editor'} %>

        <div id="audio-uploader-div" class="control-group hide" style="margin-top: -15px">
          <!--<label class="string optional control-label" for="node_file"></label>-->
          <div class="controls">
            <input type="file" id="audio-uploader" name="file" >
          </div>
        </div>

        <%= f.input :pattern, :label => '题型', :required => true, :collection => dict(Node::PATTERNS), :prompt => '请选择..' %>

        <%= f.input :choices, :label => '选择项', :required => true do %>
            <table>
              <tbody>
              <script id="choice-template" type="text/html">
                <tr>
                  <td><input type="hidden" name="node[choices_attributes][][is_answer]" value=""></td>
                  <td><input type="radio" name="node[choices_attributes][][is_answer]" value="1" title="请选定正确答案"></td>
                  <td><input type="text" name="node[choices_attributes][][content]"></td>
                  <td><a class="remove-choice btn btn-mini icon-minus-sign"></a></td>
                </tr>
              </script>
              <tr>
                <td><input type="hidden" name="node[choices_attributes][][is_answer]" value=""></td>
                <td><input type="radio" name="node[choices_attributes][][is_answer]" value="1" title="请选定正确答案"></td>
                <td><input type="text" name="node[choices_attributes][][content]"></td>
                <td><a class="remove-choice btn btn-mini icon-minus-sign"></a></td>
              </tr>

              </tbody>
              <tfoot>
              <tr>
                <td></td>
                <td colspan="2"><a class="add-choice btn btn-mini icon-plus-sign"></a></td>
              </tr>
              </tfoot>
            </table>
        <% end %>

        <!--<%= f.input :answer, :label => '正确答案', :required => true %>-->

        <%= f.input :grade, :label => '分值', :required => true %>

        <%= f.input :node_id, :label => '参考题干', :collection => @materials, :prompt => '无', :help => '如无参考材料，可留空' %>

      </fieldset>

      <div class="form-actions">
        <%= submit_tag '保存', :class => 'btn btn-primary' %>
        <a href="<%= url_for(:back) %>" class="btn">取消</a>
        <!--%= submit_tag '取消', :type => :reset, :class => "btn" %-->
      </div>

  <% end %>
</div>