config/routes.rb
Assessment::Application.routes.draw do
  devise_for :users, skip: :registrations

  resources :papers do
    resources :parts
    resources :nodes
    member do
      get 'publish', :as => 'publish'
    end
  end

  resources :organizations
  resources :members

  resources :uploads, :only => [:index, :create, :destroy]

  resources :tests do
    resources :questions do
      resource :solution
    end

    collection do
      get 'take', :as => 'take'
    end
  end

  root :to => 'dashboard#index'

end

app/models/paper.rb
class Paper < ActiveRecord::Base
  set_inheritance_column ''

  TYPES = %w[general partial]
  LANGUAGES = %w[Japanese]
  PURPOSES = %w[assess test]
  STATUS = %w[draft public deleted]

  ##----------------------------自定义状态方法---------------------------------
  def draft?
    status == 'draft'
  end

  def public?
    status == 'public'
  end

  def deleted?
    status == 'deleted'
  end

  def general?
    type == 'general'
  end

  def partial?
    type == 'partial'
  end

  def top_leaf?
    general? && !has_parts?
  end

  ##----------------------------------------属性----------------------------------------------------------------
  attr_accessible :type, :name, :notice, :score, :duration,
                  :language, :purpose, :has_parts

  ##----------------------------------------关系----------------------------------------------------------------
  belongs_to :general_paper, :class_name => 'Paper', :foreign_key => 'paper_id', :conditions => "type = 'general' and  paper_id is null"
  #只包含未删除的单项
  has_many :partial_papers, :class_name => 'Paper', :conditions => "type = 'partial' and status is null"

  has_many :nodes

  ##----------------------------------------验证----------------------------------------------------------------
  validates :type, :name, :score, :duration, :presence => true
  validates :language, :purpose, :presence => true, :if => "general?"
  validates :name, length: { maximum: 100 }
  validates :score, length: { maximum: 5 }, numericality: { only_integer: true }
  validates :duration, length: { maximum: 5 }, numericality: { only_integer: true }
  validates :score, length: { maximum: 5 },
            numericality: { only_integer: true,
                            :less_than_or_equal_to => Proc.new { |part| part.available_score},
            },
            :if => 'partial?'
  validates :score, length: { maximum: 5 },
            numericality: { only_integer: true,
                            :greater_than_or_equal_to => Proc.new { |paper| paper.already_score},
            },
            :if => 'general?'
  validates :duration, length: { maximum: 5 },
            numericality: { only_integer: true,
                            :less_than_or_equal_to => Proc.new { |part| part.available_duration},
            },
            :if => 'partial?'
  validates :duration, length: { maximum: 5 },
            numericality: { only_integer: true,
                            :greater_than_or_equal_to => Proc.new { |paper| paper.already_duration},
            },
            :if => 'general?'

  ##--------------------------------------查询方法--------------------------------------------------------------
  def already_score
    partial_papers.inject(0) {|score, part| score + part.score}
  end

  def already_duration
    partial_papers.inject(0) {|duration, part| duration + part.duration}
  end
  #此方法应用于part
  def available_score
    if new_record?
      general_paper.score - general_paper.already_score
    else
      p = Paper.find(id)
      general_paper.score - general_paper.already_score + p.score
    end
  end

  def available_duration
    if new_record?
      general_paper.duration - general_paper.already_duration
    else
      p = Paper.find(id)
      general_paper.duration - general_paper.already_duration + p.duration
    end
  end

  #查询出顶级节点，如果是material，将其下问题排序
  def top_nodes
    if partial?
      Node.find_by_sql(["select * from nodes where paper_id = ? and (type='material' or node_id is null)  order by weight asc", id]).map do |node|
        node.questions.order('weight asc') if node.material?
        node
      end
    else
      partial_papers.map {|part| part.questions }.inject(:+)
    end
  end

  # 查询出全部平铺的问题列表
  def questions
    if partial?
      #nodes.where(:depth => 1).order('weight asc').map {|node| node.material? ? node.questions.order('weight asc') : node }.flatten
      Node.find_by_sql(["select * from nodes where paper_id = ? and (type = 'material' or node_id is null) order by weight asc", id]).map {|node| node.material? ? node.questions.order('weight asc') : node }.flatten
    else
      partial_papers.map {|part| part.questions }.inject(:+)
    end
  end
end

app/controllers/papers_controller.rb
# -*- encoding : utf-8 -*-
class PapersController < ApplicationController
  add_breadcrumb '试卷列表', :papers_path

  before_filter :can_index, :only => [:index]
  before_filter :can_show, :only => [:show]
  before_filter :can_create, :only => [:new, :create]
  before_filter :can_update, :only => [:edit, :update, :destroy, :publish]

  def index
    @papers = Paper.where(:type => 'general')
  end

  def new
    @paper = Paper.new
    @paper.type = 'general'
    @paper.status = 'draft'

    add_breadcrumb '新增试卷', new_paper_path

  end

  def create
    @paper = Paper.new(params[:paper])
    @paper.status = 'draft'
    if @paper.save
      if @paper.has_parts?
        redirect_to paper_parts_path(@paper), :notice => '试卷创建成功'
      else
        redirect_to edit_paper_path(@paper), :notice => '试卷创建成功'
      end
    else
      render 'new'
    end
  end

  def show
    #@paper = Paper.find(params[:id])

    add_breadcrumb '试卷信息', paper_path(@paper)
  end

  def edit
    #@paper = Paper.find(params[:id])

    add_breadcrumb '编辑试卷', paper_path(@paper)
  end

  def update
    #@paper = Paper.find(params[:id])

    if @paper.update_attributes(params[:paper])
      redirect_to papers_path, :notice => '更新试卷成功'
    else
      render 'edit'
    end
  end

  def destroy
    #@paper = Paper.find(params[:id])

    if @paper.update_attribute(:status, :deleted)
      redirect_to papers_path
    else
      render 'index'
    end
  end

  def publish
    #@paper = Paper.find(params[:id])
    if @paper.update_attribute(:status, 'public')
      redirect_to papers_path, :notice => '发布试卷成功'
    end
  end


  private
  def can_index
    render_404 and return unless current_user.root?
  end

  def can_create
    render_404 and return unless current_user.root?
  end

  def can_show
    @paper = Paper.find(params[:id])
    render_404 and return unless current_user.root? && @paper.general?
  end

  def can_update
    @paper = Paper.find(params[:id])
    render_404 and return unless current_user.root?  && @paper.general?
    render_404 and return unless @paper.draft?
  end
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/views/papers/edit.html.erb
<% if @paper.draft? %>
    <div class="btn-group pull-right">
      <%= link_to '发布试卷', publish_paper_path, :class => 'btn btn-small btn-warning', :confirm => '发布之后将不再能编辑考题，你确认发布吗？' %>
    </div>
<% end %>

<ul class="nav nav-tabs">
  <li class="active">
    <a href="<%= edit_paper_path(@paper) %>">试题信息</a>
  </li>
  <% if @paper.has_parts? %>
      <li><a href="<%= paper_parts_path(@paper) %>" >单项设置</a></li>
      <% @paper.partial_papers.each do |part| %>
          <li><a href="<%= paper_nodes_path(part) %>"><%= part.name %></a></li>
      <% end %>
  <% else %>
      <li><a href="<%= paper_nodes_path(@paper) %>" >试卷内容</a></li>
  <% end %>
</ul>

<div class="tab-content">
  <div class="tab-pane fade in active" id="paper">

    <div id="paper-form" class="well">
      <%= simple_form_for @paper, :html => {:class => 'form-horizontal'} do |f| %>
          <fieldset>
            <legend>试卷基本信息</legend>
            <!--%= render 'form', :f => f %-->
            <%= f.input :name, :label => '试卷名称', :required => true, :help => '给你的试题取一个合适的名字，如：日语2012年JETEST' %>

            <%= f.input :language, :label => '语言', :required => true, :collection => dict(Paper::LANGUAGES), :prompt => '请选择..'  %>

            <%= f.input :purpose, :label => '试卷用途', :required => true, :collection => dict(Paper::PURPOSES), :prompt => '请选择..' %>

            <%= f.input :score, :label => '总分数', :required => true %>

            <%= f.input :duration, :label => '限时(分)', :required => true  %>

            <%= f.input :notice, :label => '注意事项', :as => 'text', :input_html => {:rows => 3} %>
          </fieldset>

          <div class="form-actions">
            <%= submit_tag '保存', :class => 'btn btn-primary' %>
            <a href="<%= url_for(:back) %>" class="btn">取消</a>
            <!--%= submit_tag '取消', :type => :reset, :class => "btn" %-->
          </div>

      <% end %>
    </div>

  </div>
</div>

app/views/papers/index.html.erb
<a href="<%= new_paper_path %>" class="btn btn-small btn-success pull-right">新增试卷</a>

<table class="table table-striped">
  <caption></caption>
  <thead>
  <tr>
    <th>试卷名称</th>
    <th>语言</th>
    <th>用途</th>
    <th>操作</th>
  </tr>
  </thead>
  <tbody>
  <% if @papers.blank? %>
      <tr placeholder>
        <td colspan="4">本综合试卷未划分单项试题</td>
      </tr>
  <% end %>
  <% @papers.each do |paper| %>
      <tr>
        <td><a href="<%= paper_path(paper) %>"><%= paper.name %></a></td>
        <td><%= paper.language %></td>
        <td><%= paper.purpose %></td>
        <td>
          <!--<a href="<%= paper_path(paper) %>" data-method="DELETE" class="btn btn-danger btn-mini">删除</a>-->
          <% if paper.public? %>
              <span class="icon-ok-sign text-success">已发布</span>
          <% elsif paper.draft? %>
              <a href="<%= edit_paper_path(paper) %>" class="btn btn-mini">编辑</a>
              <%= link_to '删除', paper_path(paper), :method => 'DELETE', :confirm => '你确定要删除此试卷吗？', :class => 'btn btn-mini btn-danger' %>
          <% elsif paper.deleted? %>
              <span class="icon-warning-sign text-warning">已删除</span>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
  <tfoot>

  </tfoot>
</table>

app/views/papers/new.html.erb
<div id="paper-form" class="well">
  <%= simple_form_for @paper, :html => {:class => 'form-horizontal'} do |f| %>
      <fieldset>
        <legend>试卷基本信息</legend>
        <!--%= render 'form', :f => f %-->
        <%= f.input :name, :label => '试卷名称', :required => true, :help => '给你的试题取一个合适的名字，如：日语2012年JETEST' %>

        <%= f.input :language, :label => '语言', :required => true, :collection => dict(Paper::LANGUAGES), :prompt => '请选择..'  %>

        <%= f.input :purpose, :label => '试卷用途', :required => true, :collection => dict(Paper::PURPOSES), :prompt => '请选择..' %>

        <%= f.input :score, :label => '总分数', :required => true %>

        <%= f.input :duration, :label => '限时(分)', :required => true  %>

        <%= f.input :notice, :label => '注意事项', :as => 'text', :input_html => {:rows => 3} %>

        <%= f.input :has_parts, :label => '划分单项', :required=> true, :help => '分单项试卷，如分为听力、语法等' %>
      </fieldset>

      <div class="form-actions">
        <%= submit_tag '保存', :class => 'btn btn-primary' %>
        <a href="<%= url_for(:back) %>" class="btn">取消</a>
        <!--%= submit_tag '取消', :type => :reset, :class => "btn" %-->
      </div>

  <% end %>
</div>

app/views/papers/show.html.erb



      <dl>
        <dt>语言：</dt>
        <dd><%= @paper.language %></dd>
        <dt>用途：</dt>
        <dd><%= @paper.purpose %></dd>
        <dt>总分：</dt>
        <dd><%= @paper.score %></dd>
        <dt>限时：</dt>
        <dd><%= @paper.duration %></dd>
      </dl>

